name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            set -e

            cd ~/portfolio
            echo "Pulling latest changes..."
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "Writing env file..."
            echo "VITE_GH_TOKEN=${{ secrets.VITE_GH_TOKEN }}" > .env

            echo "Installing dependencies..."
            npm install

            echo "Building..."
            npm run build

            echo "Deployment completed successfully!"
